name: .NET Test & Coverage
description: Restores, builds, tests, and generates a coverage report for a .NET solution.

inputs:
  solution:
    description: "Path to the solution file"
    required: true
  configuration:
    description: "Build configuration"
    required: false
    default: "Release"
  dotnet_version:
    description: ".NET SDK version"
    required: false
    default: "8.x"

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/packages.lock.json

    - name: Restore & build
      shell: pwsh
      run: |
        dotnet restore "${{ inputs.solution }}"
        dotnet build "${{ inputs.solution }}" --no-restore --configuration ${{ inputs.configuration }}

    - name: Test
      shell: pwsh
      continue-on-error: true
      run: >
        dotnet test "${{ inputs.solution }}"
        --no-build
        --configuration ${{ inputs.configuration }}
        --verbosity normal
        --logger "trx;LogFileName=tests.trx"
        --results-directory TestResults
        --collect:"XPlat Code Coverage"

    - name: Upload test results & raw coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults/**/*.trx
          **/TestResults/**/coverage.cobertura.xml

    - name: Generate coverage report
      shell: pwsh
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator `
          -reports:"**/TestResults/**/coverage.cobertura.xml" `
          -targetdir:"coverage-report" `
          -reporttypes:"MarkdownSummaryGithub;Cobertura"

    - name: Write coverage to job summary
      shell: pwsh
      run: Get-Content "coverage-report/SummaryGithub.md" >> $env:GITHUB_STEP_SUMMARY

    - name: Post coverage as PR comment
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: code-coverage
        path: coverage-report/SummaryGithub.md
