name: "Build Dependencies"
description: "Clone and build dependent repositories, then collect DLL assemblies."

inputs:
  dependencies:
    description: "Comma-separated list of dependencies."
    required: true
  configuration:
    description: "Build configuration"
    required: true
  token:
    description: "Token for accessing private repos"
    required: false
  default_org:
    description: "Default org for shorthand repos"
    required: true

outputs:
  output_dir:
    description: "Directory containing collected assemblies"
    value: ${{ steps.collect.outputs.output_dir }}

runs:
  using: "composite"
  steps:

    - name: Configure git auth
      shell: pwsh
      run: |
        if ("${{ inputs.token }}") {
          git config --global url."https://x-access-token:${{ inputs.token }}@github.com/".insteadOf "https://github.com/"
        }

    - name: Clone & build dependencies
      id: build
      shell: pwsh
      env:
        DEPENDENCIES: ${{ inputs.dependencies }}
        DEFAULT_ORG: ${{ inputs.default_org }}
        CONFIG: ${{ inputs.configuration }}
      run: |
        $ErrorActionPreference = "Stop"
        New-Item -ItemType Directory -Force -Path deps | Out-Null

        # Parse dependency list
        $list = @()
        foreach ($part in @($env:DEPENDENCIES.Split(","))) {
          $t = $part.Trim()
          if ($t) { $list += $t }
        }

        foreach ($d in $list) {
          $spec = $d
          $ref = ""

          if ($d -match "@") {
            $parts = $d.Split("@", 2)
            $spec = $parts[0].Trim()
            $ref  = $parts[1].Trim()
          }

          if ($spec.Contains("/")) {
            $owner, $repo = $spec.Split("/")
          } else {
            $owner = $env:DEFAULT_ORG
            $repo  = $spec
          }

          $folder = "$owner`_$repo"
          $url = "https://github.com/$owner/$repo.git"
          $path = "deps/$folder"

          git ls-remote $url *> $null
          git clone --depth 1 $url $path

          if ($ref) {
            Push-Location $path
            git fetch --all --tags --prune
            git checkout $ref
            Pop-Location
          }

          $sln = Get-ChildItem $path -Recurse -Filter *.sln | Select-Object -First 1
          if ($sln) {
            dotnet restore $sln.FullName
            dotnet build $sln.FullName --configuration $env:CONFIG
          }
        }

    - name: Collect assemblies
      id: collect
      shell: pwsh
      run: |
        $out = "deps-assemblies"
        New-Item -ItemType Directory -Force -Path $out | Out-Null

        Get-ChildItem -Path deps -Recurse -Include *.dll |
          Where-Object { $_.FullName -match "\\bin\\(Release|Debug)\\" } |
          Copy-Item -Destination $out -Force

        echo "output_dir=$out" >> $env:GITHUB_OUTPUT
