name: "Prepare .NET dependency assemblies"
description: "Clone, build dependency repos, and collect assemblies into a folder"

inputs:
  dependencies:
    description: "Ordered, comma-separated list like 'RepoA@main, RepoB, OtherOrg/RepoC@v1.2.3'"
    required: false
    default: ""
  configuration:
    description: "Build configuration"
    required: false
    default: "Release"
  default_org:
    description: "Default org/owner to assume when 'Owner/' prefix is omitted"
    required: false
    default: ""
  token:
    description: "Token with read access to private repos (falls back to GITHUB_TOKEN)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Keep this small here; heavy logic is in scripts.
    - name: Configure git auth (token for private repos)
      shell: pwsh
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        if (-not [string]::IsNullOrEmpty($env:TOKEN)) {
          git config --global url."https://x-access-token:$($env:TOKEN)@github.com/".insteadOf "https://github.com/"
        }

    - name: Clone dependencies (ordered; same-org or cross-org)
      shell: pwsh
      env:
        DEPENDENCIES: ${{ inputs.dependencies }}
        DEFAULT_ORG: ${{ inputs.default_org }}
        TOKEN: ${{ inputs.token }}
      run: |
        & "${{ github.action_path }}/scripts/Clone-Dependencies.ps1"

    - name: Build dependencies
      shell: pwsh
      env:
        CONFIG: ${{ inputs.configuration }}
      run: |
        & "${{ github.action_path }}/scripts/Build-Dependencies.ps1"

    - name: Collect dependency assemblies (bin/Release|Debug)
      shell: pwsh
      run: |
        & "${{ github.action_path }}/scripts/Collect-Assemblies.ps1"